openapi: 3.1.0
info:
  version: 1.0.0
  title: Control Panel - Bizyhive suit
  # contact:
  #   email: contact@example.com
  #   url: http://example.com/contact
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://adorithm.com/assets/apps/bizyhive/ecommerce-control-panel/logo.png
  description: >
    Control Panel (part of Bizyhive suit) API is a RESTful interface that exposes a collection of resources associated with a Control Panel's account and even more.


    **Available resources**

    - **Authentication**: This resource provides various methods for creating and managing various methods for authenticating and managing a user's accounts.

    - **Company data**: This resource provides various methods for managing the data of an application-contracted company.

    - **Email integrations**: This resource provides various methods for the creation and harmonious management of emails connected to the company's application (via SMTP).

    - **Company's warehouses**: This resource provides methods for the creation and management of a set of warehouses belonging to the company and storing its products, in order to properly regulate the allocation and distribution of its products.

    - **Connected users**: This resource provides all the methods given for managing the users connected to the company, managing the rights to use the application as well as their information on the part of the administrators.

    - **Contacts system**: This resource provides all methods given for creating and managing contacts and all associated items.

    - **Dashboard stats**: This resource provides all methods for getting and accessing statistics displayed in the application dashboard.

    - **Employees system**: This resource provides all the methods for creating and managing the tabs of the company's employees and workers. The tab provides personal data as well as data related to the work environment, such as working hours.

    - **Famous products**: This resource provides methods for accessing popular products in general or by category.

    - **Orders system**: This resource provides methods for creating, accessing and optimally managing orders for each company.

    - **Products system**: This resource provides methods for creating and fully managing the products that each company markets and manages.

    - **Products inventories**: This resource provides methods to manage the product inventories and them settings
    
    - **Total sales amount**: This resource provides methods for accessing sales statistics.

    - **Newsletter system**: System for managing, creating and sending emails (newsletter) to the company's customers.


    **Servers**

    - https://localhost:8080/api

    - https://control-panel.bizyhive.com/api


tags:
  - name: Authentication
    description: API EndPoints for Authentication.
  - name: Company data
    description: API EndPoints for Company data.
  - name: Email integrations
    description: API EndPoints for Email integrations.
  - name: Company's warehouses
    description: API EndPoints for Company's warehouses
  - name: Connected users
    description: API EndPoints for Connected users
  - name: Contacts system
    description: API EndPoints for Contacts system
  - name: Dashboard stats
    description: API EndPoints for Dashboard stats
  - name: Employees system
    description: API EndPoints for Employees system
  - name: Famous products
    description: API EndPoints for Famous products
  - name: Orders system
    description: API EndPoints for Orders system
  - name: Products system
    description: API EndPoints for Products system
  - name: Products inventories
    description: API EndPoints for Products inventories
  - name: Total sales amount
    description: API EndPoints for Total sales amount
  - name: Newsletter system
    description: API EndPoints for Newsletter system
servers:
  - url: https://localhost:8080/api
  - url: https://control-panel.bizyhive.com/api
paths:
  /auth/login:
    $ref: paths/authentication/login.yaml
  /auth/register:
    $ref: paths/authentication/register.yaml
  /auth/email-activation:
    $ref: paths/authentication/email-activation.yaml
  /auth/request-new-password:
    $ref: paths/authentication/request-new-password.yaml
  /auth/check-password-change-token:
    $ref: paths/authentication/check-password-change-token.yaml
  /auth/change-password:
    $ref: paths/authentication/change-password.yaml
  /auth/logout:
    $ref: paths/authentication/logout.yaml
  /auth/change-password-directly:
    $ref: paths/authentication/change-password-directly.yaml
  /authentication/account/security/2fa/email/authentication-code/send-email:
    $ref: paths/authentication/authentication-2fa-send-email.yaml
  /settings/account/security/2fa/email/activate:
    $ref: paths/authentication/activate-2fa-mechanism-via-email.yaml
  /settings/account/security/2fa/email/de-activate:
    $ref: paths/authentication/deActivate-2fa-mechanism-via-email.yaml
  /authentication/account/security/2fa/email/authentication-code/check:
    $ref: paths/authentication/authentication-2fa-check-email.yaml
  /authentication/account/security/2fa/app/authentication-code/key:
    $ref: paths/authentication/authentication-2fa-app-secret.yaml
  /settings/accouns/security/2fa/app/enable:
    $ref: paths/authentication/activate-2fa-mechanism-via-app.yaml
  /settings/account/security/2fa/app/disable:
    $ref: paths/authentication/deActivate-2fa-mechanism-via-app.yaml
  /authentication/account/security/2fa/app/authentication-code/verify:
    $ref: paths/authentication/verify-authentication-code-2fa-app.yaml
  /settings/company-data/get:
    $ref: paths/company-data/get-company-data.yaml
  /settings/company-data/save-logo:
    $ref: paths/company-data/save-logo.yaml
  /api/settings/company-data/add-new-rec:
    $ref: paths/company-data/add-company-data.yaml
  /settings/company-data/update/{rec_id}:
    $ref: paths/company-data/update-company-data.yaml
  /settings/company-data/slug/check-exists:
    $ref: paths/company-data/slug-exists.yaml
  /account/settings/company-emails:
    $ref: paths/email-integrations/get-emails.yaml
  /account/settings/company-emails/new:
    $ref: paths/email-integrations/new-email.yaml
  /account/settings/company-emails/{email_id}:
    $ref: paths/email-integrations/spec-email.yaml
  /account/settings/company-emails/test/test-email:
    $ref: paths/email-integrations/test-email.yaml
  /settings/company-data/warehouses:
    $ref: paths/company-warehouses/get-warehouses.yaml
  /settings/company-data/warehouses/{warehouse_id}:
    $ref: paths/company-warehouses/spec-warehouse.yaml
  /settings/company-data/warehouses/w/add:
    $ref: paths/company-warehouses/new-warehouse.yaml
  /settings/connected-users/list:
    $ref: paths/connected-users/get-users.yaml
  /settings/connected-users/user/(user_id):
    $ref: paths/connected-users/spec-user.yaml
  /settings/connected-users/user/u/new:
    $ref: paths/connected-users/new-user.yaml
  /settings/connected-users/user/{user_id}/privileges:
    $ref: paths/connected-users/modify-privileges.yaml
  /settings/connected-users/user/{user_id}/password/change:
    $ref: paths/connected-users/change-user-password.yaml
  /settings/connected-users/primary-account:
    $ref: paths/connected-users/get-primary-account.yaml
  /settings/connected-users/resend-verification-email:
    $ref: paths/connected-users/resend-verification-email.yaml
  /manage/contacts/list:
    $ref: paths/contacts-system/get-contacts-list.yaml
  /manage/contacts/specific-list:
    $ref: paths/contacts-system/specific-contacts-list.yaml
  /manage/contacts/{contact_id}:
    $ref: paths/contacts-system/spec-contact.yaml
  /manage/contacts/n/new:
    $ref: paths/contacts-system/new-contact.yaml
  /manage/contacts/{contact_id}/p/photo-manage:
    $ref: paths/contacts-system/contact-image-save.yaml
  /manage/contacts/{contact_id}/p/favorite:
    $ref: paths/contacts-system/contact-favorite-status.yaml
  /manage/contacts/{contact_id}/labels/list:
    $ref: paths/contacts-system/contact-labels-get-list.yaml
  /manage/contacts/{contact_id}/labels/{label_id}:
    $ref: paths/contacts-system/spec-contact-label.yaml
  /manage/contacts/{contact_id}/labels/new:
    $ref: paths/contacts-system/new-contact-label.yaml
  /manage/contacts/labels/names/list:
    $ref: paths/contacts-system/contact-labels-names-list.yaml
  /manage/contacts/labels/names/{label_id}:
    $ref: paths/contacts-system/spec-contact-label-name.yaml
  /manage/contacts/labels/names/new:
    $ref: paths/contacts-system/new-spec-contact-label-name.yaml
  /dashboard/stats/all:
    $ref: paths/dashboard-stats/all.yaml
  /manage/employees/list:
    $ref: paths/employees-system/employee.yaml
  /manage/employees/{employee_id}:
    $ref: paths/employees-system/spec-employee.yaml
  /manage/employees/l/new:
    $ref: paths/employees-system/new-employee.yaml
  /manage/employees/{employee_id}/payments/list:
    $ref: paths/employees-system/employee-payments-list.yaml
  /manage/employees/{employee_id}/payments/{payment_id}:
    $ref: paths/employees-system/employee-spec-payment.yaml
  /manage/employees/{employee_id}/payments/l/new:
    $ref: paths/employees-system/employee-new-payment.yaml
  /manage/employees/{employee_id}/payments/done/list:
    $ref: paths/employees-system/employee-done-payments-list.yaml
  /manage/employees/{employee_id}/payments/done/specific-list:
    $ref: paths/employees-system/employee-done-payments-spec-list.yaml
  /manage/employees/{employee_id}/payments/done/m/{payment_id}:
    $ref: paths/employees-system/employee-spec-done-payment.yaml
  /manage/employees/{employee_id}/payments/done/new:
    $ref: paths/employees-system/employee-new-done-payment.yaml
  /manage/employees/{employee_id}/work-hours:
    $ref: paths/employees-system/employee-worked-hours-list.yaml
  /manage/employees/{employee_id}/work-hours-specific:
    $ref: paths/employees-system/employee-worked-hours-spec-list.yaml
  /manage/employees/{employee_id}/work-hours/{rec_id}:
    $ref: paths/employees-system/employee-spec-worked-hour.yaml
  /manage/employees/{employee_id}/work-hours/n/new:
    $ref: paths/employees-system/employee-new-worked-hour.yaml
  /manage/employees/{employee_id}/work-hours/n/new-multiple-days:
    $ref: paths/employees-system/employee-new-worked-hour-multiple.yaml
  /ecommerce/store/products/famous/list:
    $ref: paths/famous-products/general-list.yaml
  /ecommerce/store/products/famous/list-category:
    $ref: paths/famous-products/categories-list.yaml
  /manage/newsletter/messages/list:
    $ref: paths/newsletters-system/messages-list.yaml
  /manage/newsletter/messages/specific-message:
    $ref: paths/newsletters-system/message.yaml
  /ecommerce/store/orders/orders:
    $ref: paths/orders-system/general-list.yaml
  /ecommerce/store/orders/specific-orders:
    $ref: paths/orders-system/specific-list.yaml
  /ecommerce/store/orders/summary/count/all:
    $ref: paths/orders-system/order-summary-all.yaml
  /ecommerce/store/orders/summary/count/specific:
    $ref: paths/orders-system/order-summary-specific.yaml
  /ecommerce/store/orders/summary/count/spec-date-range:
    $ref: paths/orders-system/order-summary-date-range.yaml
  /ecommerce/store/orders/{order_id}:
    $ref: paths/orders-system/spec-order.yaml
  /ecommerce/store/orders/ord/new:
    $ref: paths/orders-system/new-order.yaml
  /ecommerce/store/orders/{order_id}/{new_status}:
    $ref: paths/orders-system/order-status.yaml
  /ecommerce/store/orders/{order_id}/notes:
    $ref: paths/orders-system/update-order-notes.yaml
  /ecommerce/store/orders/{order_id}/order-seen:
    $ref: paths/orders-system/update-order-seen.yaml
  /ecommerce/store/orders/upload-paper:
    $ref: paths/orders-system/upload-order-papers.yaml
  /ecommerce/store/orders/upload-paper/{paper_id}:
    $ref: paths/orders-system/delete-order-paper.yaml
  /ecommerce/store/orders/search/global-search:
    $ref: paths/orders-system/search-orders.yaml
  /ecommerce/store/orders/{order_id}/products:
    $ref: paths/orders-system/get-orders-products.yaml
  /ecommerce/store/orders/{order_id}/products/{product_id}:
    $ref: paths/orders-system/get-spec-orders-product.yaml
  /ecommerce/store/orders/{order_id}/products/{product_id}/{status}:
    $ref: paths/orders-system/order-product-status.yaml
  /payments/methods/list/active:
    $ref: paths/orders-system/order-payment-method-list.yaml
  /payments/methods/{payment_id}:
    $ref: paths/orders-system/spec-order-payment-method.yaml
  /ecommerce/store/products/products:
    $ref: paths/products-system/get-list.yaml
  /ecommerce/store/products/specific-products:
    $ref: paths/products-system/specific-list.yaml
  /ecommerce/store/products/{product}:
    $ref: paths/products-system/spec-product.yaml
  /ecommerce/store/products/new:
    $ref: paths/products-system/new-product.yaml
  /ecommerce/store/products/{product_id}/notes/update:
    $ref: paths/products-system/update-product-notes.yaml
  /ecommerce/store/{product_id}/categories/update:
    $ref: paths/products-system/update-categories.yaml
  /ecommerce/store/products/{product_id}/get-shared-product:
    $ref: paths/products-system/get-shared-product.yaml
  /ecommerce/store/products/{product_id}/{status}:
    $ref: paths/products-system/update-product-status.yaml
  /ecommerce/store/products/search/global-search:
    $ref: paths/products-system/product-search.yaml
  /ecommerce/store/products/{product_id}/upload-image:
    $ref: paths/products-system/upload-product-image-single.yaml
  /ecommerce/store/products/{product_id}/upload-multiple-image:
    $ref: paths/products-system/upload-product-image-multiple.yaml
  /ecommerce/store/products/images/delete/{image_id}:
    $ref: paths/products-system/delete-product-image.yaml
  /ecommerce/store/products/categories/list:
    $ref: paths/products-system/product-categories-list.yaml
  /ecommerce/store/products/c/categories/{pcategory_id}:
    $ref: paths/products-system/specific-product-categories.yaml
  /ecommerce/store/products/categories/new:
    $ref: paths/products-system/new-product-category.yaml
  /ecommerce/store/products/{product}/product-transactions:
    $ref: paths/products-system/get-product-transactions.yaml
  /products/inventories:
    $ref: paths/product-inventories/get-list.yaml
  /products/inventories-specific-data:
    $ref: paths/product-inventories/get-basic-data-list.yaml
  /products/inventories/{inventory_id}:
    $ref: paths/product-inventories/get-spec-inventory.yaml
  /products/inventories/n/new:
    $ref: paths/product-inventories/new-inventory.yaml