get:
  tags:
    - Products system
  summary: Get categories list
  description: |
    Get categories list
  operationId: getProductCategoriesList
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                pcategory_id:
                  type: string
                label:
                  type: string
                connected_account_id:
                  type: string
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: number
                example: 500
              type:
                type: string
                example: internal_server_error
              message:
                type: object | string
                example: {}